//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Scripts/PlayerScripts/Player Controller/PlayerController.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerController : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerController()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerController"",
    ""maps"": [
        {
            ""name"": ""Gameplay"",
            ""id"": ""3eaa763b-b31e-4256-8c3d-8392048d7997"",
            ""actions"": [
                {
                    ""name"": ""MovementGamepad"",
                    ""type"": ""PassThrough"",
                    ""id"": ""edd9e4fd-3b3b-4389-8144-902db3a808fb"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MovementKBAM"",
                    ""type"": ""PassThrough"",
                    ""id"": ""4f08b975-50fb-47c9-8966-1c05e9524168"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Rotation"",
                    ""type"": ""PassThrough"",
                    ""id"": ""e95313ae-46b8-4064-9b6f-d73e48b6303e"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""MousePosition"",
                    ""type"": ""PassThrough"",
                    ""id"": ""f4003f83-11f0-4b7b-8d0d-7af72e0368f5"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SwingSword"",
                    ""type"": ""Button"",
                    ""id"": ""fa7bbc7e-b0c1-498b-a4e0-98a30efa55cb"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Evade"",
                    ""type"": ""Button"",
                    ""id"": ""48287197-12d2-4158-b648-9f8b106924dd"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""UseCardLeft"",
                    ""type"": ""Button"",
                    ""id"": ""a6a8bb34-12ad-417c-b24f-8c967fbd335a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""UseCardRight"",
                    ""type"": ""Button"",
                    ""id"": ""ba594b6e-3e60-4932-8e8a-56e0d929b36a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""SwitchInputMode"",
                    ""type"": ""Button"",
                    ""id"": ""27878c63-fc7d-4c17-be51-9de1f61908e5"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""f2e325b5-322b-41b3-a531-255710e53818"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovementGamepad"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a8b614d7-4ad7-45fe-b2f1-ea175f380b7e"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Rotation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""90361867-6a80-4e16-b4a7-fa31b587419b"",
                    ""path"": ""<Mouse>/position"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MousePosition"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8e1d9176-9670-46d4-b402-4b362b87f1d4"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwingSword"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""daeb3be0-6661-4fc2-8018-32abe765ff56"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwingSword"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""2D Vector"",
                    ""id"": ""e62f2b59-8c3a-4f52-af46-41e15042bb7d"",
                    ""path"": ""2DVector"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovementKBAM"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""up"",
                    ""id"": ""d2010e3c-0a90-43ae-b433-c68fbd5b4466"",
                    ""path"": ""<Keyboard>/w"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovementKBAM"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""down"",
                    ""id"": ""81e00286-804d-4ebb-a44b-19c99d62acc4"",
                    ""path"": ""<Keyboard>/s"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovementKBAM"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""left"",
                    ""id"": ""0a980e71-a654-41a4-9d29-5645fe4d70e4"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovementKBAM"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""right"",
                    ""id"": ""e8f91709-52d4-4019-83b9-a481e90f1103"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MovementKBAM"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""dba81bae-5c49-40eb-8652-2e24a6ef1240"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Evade"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a7ed789e-3ec4-4a04-98da-ffdeec43fdf6"",
                    ""path"": ""<Gamepad>/leftStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Evade"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9ac673c2-a773-4305-aaa0-88b122610c02"",
                    ""path"": ""<Keyboard>/q"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UseCardLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f17228c9-5433-4ffa-be2b-ae989919aad3"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UseCardLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""a377a896-d63f-4b03-80b0-44aa3c6e2162"",
                    ""path"": ""<Keyboard>/e"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UseCardRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""e8c2954e-5efd-4c9d-b5b1-4cb5b7a14b68"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""UseCardRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ba2fc28e-173c-4da3-9709-2698015286ab"",
                    ""path"": ""<Keyboard>/c"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwitchInputMode"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""bfab65d4-ccd8-44da-b9d2-d48a607d7f5c"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SwitchInputMode"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Gameplay
        m_Gameplay = asset.FindActionMap("Gameplay", throwIfNotFound: true);
        m_Gameplay_MovementGamepad = m_Gameplay.FindAction("MovementGamepad", throwIfNotFound: true);
        m_Gameplay_MovementKBAM = m_Gameplay.FindAction("MovementKBAM", throwIfNotFound: true);
        m_Gameplay_Rotation = m_Gameplay.FindAction("Rotation", throwIfNotFound: true);
        m_Gameplay_MousePosition = m_Gameplay.FindAction("MousePosition", throwIfNotFound: true);
        m_Gameplay_SwingSword = m_Gameplay.FindAction("SwingSword", throwIfNotFound: true);
        m_Gameplay_Evade = m_Gameplay.FindAction("Evade", throwIfNotFound: true);
        m_Gameplay_UseCardLeft = m_Gameplay.FindAction("UseCardLeft", throwIfNotFound: true);
        m_Gameplay_UseCardRight = m_Gameplay.FindAction("UseCardRight", throwIfNotFound: true);
        m_Gameplay_SwitchInputMode = m_Gameplay.FindAction("SwitchInputMode", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Gameplay
    private readonly InputActionMap m_Gameplay;
    private IGameplayActions m_GameplayActionsCallbackInterface;
    private readonly InputAction m_Gameplay_MovementGamepad;
    private readonly InputAction m_Gameplay_MovementKBAM;
    private readonly InputAction m_Gameplay_Rotation;
    private readonly InputAction m_Gameplay_MousePosition;
    private readonly InputAction m_Gameplay_SwingSword;
    private readonly InputAction m_Gameplay_Evade;
    private readonly InputAction m_Gameplay_UseCardLeft;
    private readonly InputAction m_Gameplay_UseCardRight;
    private readonly InputAction m_Gameplay_SwitchInputMode;
    public struct GameplayActions
    {
        private @PlayerController m_Wrapper;
        public GameplayActions(@PlayerController wrapper) { m_Wrapper = wrapper; }
        public InputAction @MovementGamepad => m_Wrapper.m_Gameplay_MovementGamepad;
        public InputAction @MovementKBAM => m_Wrapper.m_Gameplay_MovementKBAM;
        public InputAction @Rotation => m_Wrapper.m_Gameplay_Rotation;
        public InputAction @MousePosition => m_Wrapper.m_Gameplay_MousePosition;
        public InputAction @SwingSword => m_Wrapper.m_Gameplay_SwingSword;
        public InputAction @Evade => m_Wrapper.m_Gameplay_Evade;
        public InputAction @UseCardLeft => m_Wrapper.m_Gameplay_UseCardLeft;
        public InputAction @UseCardRight => m_Wrapper.m_Gameplay_UseCardRight;
        public InputAction @SwitchInputMode => m_Wrapper.m_Gameplay_SwitchInputMode;
        public InputActionMap Get() { return m_Wrapper.m_Gameplay; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(GameplayActions set) { return set.Get(); }
        public void SetCallbacks(IGameplayActions instance)
        {
            if (m_Wrapper.m_GameplayActionsCallbackInterface != null)
            {
                @MovementGamepad.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnMovementGamepad;
                @MovementGamepad.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnMovementGamepad;
                @MovementGamepad.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnMovementGamepad;
                @MovementKBAM.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnMovementKBAM;
                @MovementKBAM.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnMovementKBAM;
                @MovementKBAM.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnMovementKBAM;
                @Rotation.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnRotation;
                @Rotation.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnRotation;
                @Rotation.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnRotation;
                @MousePosition.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnMousePosition;
                @MousePosition.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnMousePosition;
                @MousePosition.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnMousePosition;
                @SwingSword.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnSwingSword;
                @SwingSword.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnSwingSword;
                @SwingSword.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnSwingSword;
                @Evade.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnEvade;
                @Evade.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnEvade;
                @Evade.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnEvade;
                @UseCardLeft.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnUseCardLeft;
                @UseCardLeft.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnUseCardLeft;
                @UseCardLeft.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnUseCardLeft;
                @UseCardRight.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnUseCardRight;
                @UseCardRight.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnUseCardRight;
                @UseCardRight.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnUseCardRight;
                @SwitchInputMode.started -= m_Wrapper.m_GameplayActionsCallbackInterface.OnSwitchInputMode;
                @SwitchInputMode.performed -= m_Wrapper.m_GameplayActionsCallbackInterface.OnSwitchInputMode;
                @SwitchInputMode.canceled -= m_Wrapper.m_GameplayActionsCallbackInterface.OnSwitchInputMode;
            }
            m_Wrapper.m_GameplayActionsCallbackInterface = instance;
            if (instance != null)
            {
                @MovementGamepad.started += instance.OnMovementGamepad;
                @MovementGamepad.performed += instance.OnMovementGamepad;
                @MovementGamepad.canceled += instance.OnMovementGamepad;
                @MovementKBAM.started += instance.OnMovementKBAM;
                @MovementKBAM.performed += instance.OnMovementKBAM;
                @MovementKBAM.canceled += instance.OnMovementKBAM;
                @Rotation.started += instance.OnRotation;
                @Rotation.performed += instance.OnRotation;
                @Rotation.canceled += instance.OnRotation;
                @MousePosition.started += instance.OnMousePosition;
                @MousePosition.performed += instance.OnMousePosition;
                @MousePosition.canceled += instance.OnMousePosition;
                @SwingSword.started += instance.OnSwingSword;
                @SwingSword.performed += instance.OnSwingSword;
                @SwingSword.canceled += instance.OnSwingSword;
                @Evade.started += instance.OnEvade;
                @Evade.performed += instance.OnEvade;
                @Evade.canceled += instance.OnEvade;
                @UseCardLeft.started += instance.OnUseCardLeft;
                @UseCardLeft.performed += instance.OnUseCardLeft;
                @UseCardLeft.canceled += instance.OnUseCardLeft;
                @UseCardRight.started += instance.OnUseCardRight;
                @UseCardRight.performed += instance.OnUseCardRight;
                @UseCardRight.canceled += instance.OnUseCardRight;
                @SwitchInputMode.started += instance.OnSwitchInputMode;
                @SwitchInputMode.performed += instance.OnSwitchInputMode;
                @SwitchInputMode.canceled += instance.OnSwitchInputMode;
            }
        }
    }
    public GameplayActions @Gameplay => new GameplayActions(this);
    public interface IGameplayActions
    {
        void OnMovementGamepad(InputAction.CallbackContext context);
        void OnMovementKBAM(InputAction.CallbackContext context);
        void OnRotation(InputAction.CallbackContext context);
        void OnMousePosition(InputAction.CallbackContext context);
        void OnSwingSword(InputAction.CallbackContext context);
        void OnEvade(InputAction.CallbackContext context);
        void OnUseCardLeft(InputAction.CallbackContext context);
        void OnUseCardRight(InputAction.CallbackContext context);
        void OnSwitchInputMode(InputAction.CallbackContext context);
    }
}
